version: '3.3'
services:

  API:
    container_name: API
    image: kruiz9/api_p2_201603009
    ports:
      - 8080:8080
    networks:
     db_network:
       ipv4_address: 192.168.20.15


  FRONT:
    container_name: FRONT
    image: kruiz9/front_p2_201603009
    ports:
      - 80:80
    depends_on:
      - API
    environment:
      API_HOST: API:8080
    networks:
     db_network:
       ipv4_address: 192.168.20.9
     
     
networks:
  db_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.20.0/24
