version: '3.3'
services:
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'proyecto_1'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'usuario'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
      
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 1s
      retries: 1
      
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mydb_temp:/var/lib/mysql
    networks:
     db_network:
       ipv4_address: 197.0.0.2
       
       
      
      
      
  api:
    container_name: api
    image: api_proyecto_1
    depends_on:
      - db
    ports:
      - '8080:8080'
    links: 
      - db
    environment:
      MYSQL_IP: 197.0.0.2
    networks:
     db_network:
       ipv4_address: 197.0.0.3  
      


    
    
  front:
    container_name: front
    image: front_proyecto_1
    depends_on:
      - api
    ports:
      - '80:80'
    links: 
      - api
    environment:
      REACT_APP_IP: 197.0.0.2
    networks:
     db_network:
       ipv4_address: 197.0.0.4
      
      

      
      
networks:
  db_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 197.0.0.0/24


# Names our volume
volumes:
  mydb_temp: 
  
